export const MOCK_ALBUMS = [
  {
    id: 'popular_hits',
    name: 'Popular Hits',
    coverImage: '/static/images/popular_hits.jpg',
    releaseYear: 2026,
    artist: 'Various Artists',
    description: 'The top trending hits from around the globe.',
    songs: [
      { id: 'av1', name: 'Buttabomma', duration: 198, genre: 'Dance Pop', audioUrl: '/static/audio/buttabomma.mp3' },
      { id: 's3', name: 'Srivalli', duration: 224, genre: 'Dance Pop', audioUrl: '/static/audio/srivalli.mp3' },
      { id: 'gg1', name: 'Inkem Inkem Inkem Kaavaale', duration: 262, genre: 'Romantic Melody', audioUrl: '/static/audio/inkem_inkem.mp3' },
      { id: 'av2', name: 'Samajavaragamana', duration: 214, genre: 'Romantic Melody', audioUrl: '/static/audio/samajavaragamana.mp3' },
      { id: 'ary1', name: 'Feel My Love', duration: 290, genre: 'Romantic Melody', audioUrl: '/static/audio/feel_my_love.mp3' },
      { id: 'ssr1', name: 'Pranavalaya', duration: 243, genre: 'Classical Fusion', audioUrl: '/static/audio/pranavalaya.mp3' },
      { id: 'mag1', name: 'Panchadara Bomma', duration: 280, genre: 'Romantic Melody', audioUrl: '/static/audio/panchadara_bomma.mp3' },
      { id: 'ped1', name: 'Chikiri Chikiri', duration: 248, genre: 'Classical Fusion', audioUrl: '/static/audio/chikiri_chikiri.mp3' },
      { id: 'os1', name: 'Electronic Summer', duration: 180, genre: 'Electronic', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3' },
      { id: 'os2', name: 'Chill Synthwave', duration: 210, genre: 'Synthwave', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3' },
      { id: 'os3', name: 'Deep Bass Drop', duration: 240, genre: 'Dance Pop', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3' },
      { id: 'os6', name: 'Midnight Outrun', duration: 198, genre: 'Synthwave', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3' },
      { id: 'os7', name: 'Lofi Sleep Cafe', duration: 215, genre: 'Lofi', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3' },
      { id: 'os8', name: 'Golden Hour Acoustic', duration: 172, genre: 'Acoustic', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3' },
      { id: 'os11', name: 'Club Dance Arena', duration: 254, genre: 'Dance Pop', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3' },
      { id: 'os12', name: 'Late Night Jazz Session', duration: 219, genre: 'Jazz', audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3' },
    ],
  },
  {
    id: 'ye_maaya_chesave',
    name: 'Ye Maaya Chesave',
    coverImage: '/static/images/ye_maaya_chesave.jpg',
    releaseYear: 2010,
    artist: 'A. R. Rahman',
    description: 'The iconic romantic soundtrack composed by Mozart of Madras A. R. Rahman.',
    songs: [
      { id: 'ymc1', name: 'Aaromale', duration: 338, genre: 'Romantic Melody', audioUrl: '/static/audio/aaromale.mp3' },
      { id: 'ymc2', name: 'Ee Hridayam', duration: 324, genre: 'Romantic Melody', audioUrl: '/static/audio/ee_hridayam.mp3' },
      { id: 'ymc3', name: 'Kundanapu Bomma', duration: 300, genre: 'Romantic Melody', audioUrl: '/static/audio/kundanapu_bomma.mp3' },
      { id: 'ymc4', name: 'Manasaa', duration: 248, genre: 'Romantic Melody', audioUrl: '/static/audio/manasaa.mp3' },
      { id: 'ymc5', name: 'Swaasye', duration: 190, genre: 'Romantic Melody', audioUrl: '/static/audio/swaasye.mp3' },
      { id: 'ymc6', name: 'Vintunnavaa', duration: 408, genre: 'Romantic Melody', audioUrl: '/static/audio/vintunnavaa.mp3' },
    ],
  },
  {
    id: 'rangasthalam',
    name: 'Rangasthalam',
    coverImage: '/static/images/rangasthalam.jpg',
    releaseYear: 2018,
    artist: 'Devi Sri Prasad',
    description: 'A rustic and soulful classic folk-album composed by Devi Sri Prasad.',
    songs: [
      { id: 'ran1', name: 'Rangamma Mangamma', duration: 264, genre: 'Romantic Melody', audioUrl: '/static/audio/rangamma_mangamma.mp3' },
      { id: 'ran2', name: 'Aa Gattununtaava', duration: 207, genre: 'Romantic Melody', audioUrl: '/static/audio/aa_gattununtaava.mp3' },
      { id: 'ran3', name: 'Jigelu Rani', duration: 307, genre: 'Dance Pop', audioUrl: '/static/audio/jigelu_rani.mp3' },
      { id: 'ran4', name: 'Orayyo', duration: 339, genre: 'Romantic Melody', audioUrl: '/static/audio/orayyo.mp3' },
      { id: 'ran5', name: 'Ranga Ranga', duration: 319, genre: 'Dance Pop', audioUrl: '/static/audio/ranga_ranga.mp3' },
      { id: 'ran6', name: 'Yentha Sakkagunnave', duration: 281, genre: 'Romantic Melody', audioUrl: '/static/audio/yentha_sakkagunnave.mp3' },
    ],
  },
  {
    id: 'arya',
    name: 'Arya',
    coverImage: '/static/images/arya.jpg',
    releaseYear: 2004,
    artist: 'Devi Sri Prasad',
    description: 'The energetic youth anthem album composed by Devi Sri Prasad.',
    songs: [
      { id: 'ary1', name: 'Feel My Love', duration: 290, genre: 'Romantic Melody', audioUrl: '/static/audio/feel_my_love.mp3' },
      { id: 'ary2', name: 'Nuvvunte', duration: 309, genre: 'Romantic Melody', audioUrl: '/static/audio/nuvvunte.mp3' },
      { id: 'ary3', name: 'You Rock My World', duration: 294, genre: 'Dance Pop', audioUrl: '/static/audio/you_rock_my_world.mp3' },
      { id: 'ary4', name: 'O My Brotheru', duration: 297, genre: 'Dance Pop', audioUrl: '/static/audio/o_my_brotheru.mp3' },
      { id: 'ary5', name: 'Thakadimithom', duration: 325, genre: 'Classical Fusion', audioUrl: '/static/audio/thakadimithom.mp3' },
      { id: 'ary6', name: 'Aa Ante Amalapuram', duration: 295, genre: 'Dance Pop', audioUrl: '/static/audio/aa_ante_amalapuram.mp3' },
    ],
  },
  {
    id: 'ala_vaikunthapurramuloo',
    name: 'Ala Vaikunthapurramuloo',
    coverImage: '/static/images/ala_vaikunthapurramuloo.jpg',
    releaseYear: 2020,
    artist: 'Thaman S',
    description: 'The monumental record-breaking musical by Thaman S.',
    songs: [
      { id: 'av1', name: 'Buttabomma', duration: 198, genre: 'Dance Pop', audioUrl: '/static/audio/buttabomma.mp3' },
      { id: 'av2', name: 'Samajavaragamana', duration: 214, genre: 'Romantic Melody', audioUrl: '/static/audio/samajavaragamana.mp3' },
      { id: 'av3', name: 'Ramuloo Ramula', duration: 240, genre: 'Dance Pop', audioUrl: '/static/audio/ramuloo_ramula.mp3' },
      { id: 'av4', name: 'OMG Daddy', duration: 220, genre: 'Dance Pop', audioUrl: '/static/audio/omg_daddy.mp3' },
      { id: 'av5', name: 'Samajavaragamana (Female)', duration: 255, genre: 'Romantic Melody', audioUrl: '/static/audio/samajavaragamana_female.mp3' },
      { id: 'av6', name: 'Sittharala Sirapadu', duration: 200, genre: 'Classical Fusion', audioUrl: '/static/audio/sittharala_sirapadu.mp3' },
      { id: 'av7', name: 'Ala Vaikunthapurramuloo Theme', duration: 203, genre: 'Classical Fusion', audioUrl: '/static/audio/ala_vaikunthapurramuloo_theme.mp3' },
    ],
  },
  {
    id: 'orange',
    name: 'Orange',
    coverImage: '/static/images/orange.jpg',
    releaseYear: 2010,
    artist: 'Harris Jayaraj',
    description: 'Soulful and iconic love tracks composed by Harris Jayaraj.',
    songs: [
      { id: 'ora1', name: 'Ola Olaala', duration: 260, genre: 'Dance Pop', audioUrl: '/static/audio/ola_olaala.mp3' },
      { id: 'ora2', name: 'Chilipiga', duration: 250, genre: 'Romantic Melody', audioUrl: '/static/audio/chilipiga.mp3' },
      { id: 'ora3', name: 'Nenu Nuvvantu', duration: 280, genre: 'Romantic Melody', audioUrl: '/static/audio/nenu_nuvvantu.mp3' },
      { id: 'ora4', name: 'Hello Rammante', duration: 282, genre: 'Dance Pop', audioUrl: '/static/audio/hello_rammante.mp3' },
      { id: 'ora5', name: 'O Range', duration: 272, genre: 'Dance Pop', audioUrl: '/static/audio/o_range.mp3' },
      { id: 'ora6', name: 'Rooba Rooba', duration: 270, genre: 'Romantic Melody', audioUrl: '/static/audio/rooba_rooba.mp3' },
    ],
  },
  {
    id: 'mirchi',
    name: 'Mirchi',
    coverImage: '/static/images/mirchi.jpg',
    releaseYear: 2013,
    artist: 'Devi Sri Prasad',
    description: 'Mass blockbustermusic tracks composed by Devi Sri Prasad.',
    songs: [
      { id: 'mir1', name: 'Mirchi Theme', duration: 85, genre: 'Classical Fusion', audioUrl: '/static/audio/mirchi_theme.mp3' },
      { id: 'mir2', name: 'Barbie Girl', duration: 240, genre: 'Dance Pop', audioUrl: '/static/audio/barbie_girl.mp3' },
      { id: 'mir3', name: 'Darlingey', duration: 230, genre: 'Dance Pop', audioUrl: '/static/audio/darlingey.mp3' },
      { id: 'mir4', name: 'Idhedho Bagundhe', duration: 270, genre: 'Romantic Melody', audioUrl: '/static/audio/idhedho_bagundhe.mp3' },
      { id: 'mir5', name: 'Nee Choopula', duration: 250, genre: 'Romantic Melody', audioUrl: '/static/audio/nee_choopula.mp3' },
      { id: 'mir6', name: 'Pandagala Digivachavu', duration: 290, genre: 'Classical Fusion', audioUrl: '/static/audio/pandagala_digivachavu.mp3' },
      { id: 'mir7', name: 'Yahoon Yahoon', duration: 280, genre: 'Dance Pop', audioUrl: '/static/audio/yahoon_yahoon.mp3' },
    ],
  },
  {
    id: 'geetha_govindam',
    name: 'Geetha Govindam',
    coverImage: '/static/images/geetha_govindham.jpg',
    releaseYear: 2018,
    artist: 'Gopi Sundar',
    description: 'The chartbuster romantic comedy soundtrack of Geetha Govindam.',
    songs: [
      { id: 'gg1', name: 'Inkem Inkem Inkem Kaavaale', duration: 262, genre: 'Romantic Melody', audioUrl: '/static/audio/inkem_inkem.mp3' },
      { id: 'gg2', name: 'Yenti Yenti', duration: 200, genre: 'Romantic Melody', audioUrl: '/static/audio/yenti_yenti.mp3' },
      { id: 'gg3', name: 'Vachindamma', duration: 240, genre: 'Romantic Melody', audioUrl: '/static/audio/vachindamma.mp3' },
      { id: 'gg4', name: 'Kanureppala Kaalam', duration: 182, genre: 'Romantic Melody', audioUrl: '/static/audio/kanureppala_kaalam.mp3' },
      { id: 'gg5', name: 'Tanemandhe Tanemandhe', duration: 200, genre: 'Romantic Melody', audioUrl: '/static/audio/tanemandhe_tanemandhe.mp3' },
      { id: 'gg6', name: 'What The F', duration: 210, genre: 'Dance Pop', audioUrl: '/static/audio/what_the_f.mp3' },
      { id: 'gg7', name: 'What The Life', duration: 210, genre: 'Dance Pop', audioUrl: '/static/audio/what_the_life.mp3' },
    ],
  },
  {
    id: 'magadheera',
    name: 'Magadheera',
    coverImage: '/static/images/magadheera.jpg',
    releaseYear: 2009,
    artist: 'M. M. Keeravani',
    description: 'The monumental periodic blockbuster soundtrack of Magadheera.',
    songs: [
      { id: 'mag1', name: 'Panchadara Bomma', duration: 280, genre: 'Romantic Melody', audioUrl: '/static/audio/panchadara_bomma.mp3' },
      { id: 'mag_nako', name: 'Nakosam Nuvu', duration: 280, genre: 'Romantic Melody', audioUrl: '/static/audio/nakosam_nuvu.mp3' },
      { id: 'mag2', name: 'Dheera Dheera', duration: 228, genre: 'Dance Pop', audioUrl: '/static/audio/dheera_dheera.mp3' },
      { id: 'mag3', name: 'Nee Kanti Chupullo', duration: 270, genre: 'Romantic Melody', audioUrl: '/static/audio/nee_kanti_chupullo.mp3' },
      { id: 'mag4', name: 'Jorsey', duration: 290, genre: 'Dance Pop', audioUrl: '/static/audio/jorsey.mp3' },
      { id: 'mag5', name: 'Bangaru Kodipetta', duration: 344, genre: 'Dance Pop', audioUrl: '/static/audio/bangaru_kodipetta.mp3' },
      { id: 'mag6', name: 'Rolling Title Music', duration: 153, genre: 'Classical Fusion', audioUrl: '/static/audio/rolling_title_music.mp3' },
    ],
  },
  {
    id: 'hi_nanna',
    name: 'Hi Nanna',
    coverImage: '/static/images/hi_nanna.jpg',
    releaseYear: 2023,
    artist: 'Hesham Abdul Wahab',
    description: 'The heartwarming and emotional soundtrack of Hi Nanna.',
    songs: [
      { id: 'hn1', name: 'Samayama', duration: 278, genre: 'Romantic Melody', audioUrl: '/static/audio/samayama.mp3' },
      { id: 'hn2', name: 'Adigaa', duration: 217, genre: 'Romantic Melody', audioUrl: '/static/audio/adigaa.mp3' },
      { id: 'hn3', name: 'Ammaadi', duration: 224, genre: 'Romantic Melody', audioUrl: '/static/audio/ammaadi.mp3' },
      { id: 'hn4', name: 'Chedhu Nijam', duration: 263, genre: 'Romantic Melody', audioUrl: '/static/audio/chedhu_nijam.mp3' },
      { id: 'hn5', name: 'Gaaju Bomma', duration: 273, genre: 'Romantic Melody', audioUrl: '/static/audio/gaaju_bomma.mp3' },
      { id: 'hn6', name: 'Needhe Needhe', duration: 204, genre: 'Romantic Melody', audioUrl: '/static/audio/needhe_needhe.mp3' },
      { id: 'hn7', name: 'Odiyamma', duration: 206, genre: 'Dance Pop', audioUrl: '/static/audio/odiyamma.mp3' },
    ],
  },
  {
    id: 'pushpa',
    name: 'Pushpa: The Rise',
    coverImage: '/static/images/pushpa.jpg',
    releaseYear: 2021,
    artist: 'Devi Sri Prasad',
    description: 'The sensational and energetic soundtrack of Pushpa: The Rise.',
    songs: [
      { id: 's3', name: 'Srivalli', duration: 224, genre: 'Dance Pop', audioUrl: '/static/audio/srivalli.mp3' },
      { id: 'p_dakko', name: 'Dakko Dakko Meka', duration: 292, genre: 'Dance Pop', audioUrl: '/static/audio/dakko_dakko_meka.mp3' },
      { id: 'p_saami', name: 'Saami Saami', duration: 223, genre: 'Romantic Melody', audioUrl: '/static/audio/saami_saami.mp3' },
      { id: 'p_oo_antava', name: 'Oo Antava Oo Oo Antava', duration: 228, genre: 'Dance Pop', audioUrl: '/static/audio/oo_antava.mp3' },
      { id: 'p_eyy_bidda', name: 'Eyy Bidda Idhi Naa Adda', duration: 234, genre: 'Dance Pop', audioUrl: '/static/audio/eyy_bidda_idhi_naa_adda.mp3' },
    ],
  },
  {
    id: 'ssr',
    name: 'Shyam Singha Roy',
    coverImage: '/static/images/shyam_singha_roy.jpg',
    releaseYear: 2021,
    artist: 'Mickey J. Meyer & Anurag Kulkarni',
    description: 'The complete periodic drama soundtrack for Shyam Singha Roy.',
    songs: [
      { id: 'ssr1', name: 'Pranavalaya', duration: 243, genre: 'Classical Fusion', audioUrl: '/static/audio/pranavalaya.mp3' },
      { id: 'ssr2', name: 'Sirivennela', duration: 255, genre: 'Romantic Melody', audioUrl: '/static/audio/sirivennela.mp3' },
      { id: 'ssr3', name: 'Sirivennela (Female)', duration: 182, genre: 'Romantic Melody', audioUrl: '/static/audio/sirivennela_female.mp3' },
      { id: 'ssr4', name: 'Edo Edo', duration: 202, genre: 'Romantic Melody', audioUrl: '/static/audio/edo_edo.mp3' },
      { id: 'ssr5', name: 'Tara', duration: 172, genre: 'Romantic Melody', audioUrl: '/static/audio/tara.mp3' },
    ],
  },
  {
    id: 'son_of_satyamurthy',
    name: 'Son of Satyamurthy',
    coverImage: '/static/images/son_of_satyamurthy.jpg',
    releaseYear: 2015,
    artist: 'Devi Sri Prasad',
    description: 'The blockbuster energy-packed soundtrack composed by Devi Sri Prasad.',
    songs: [
      { id: 'sos1', name: 'Chal Chalo Chalo', duration: 355, genre: 'Dance Pop', audioUrl: '/static/audio/chal_chalo_chalo.mp3' },
      { id: 'sos2', name: 'Come To The Party', duration: 287, genre: 'Dance Pop', audioUrl: '/static/audio/come_to_the_party.mp3' },
      { id: 'sos3', name: 'Jaaruko', duration: 308, genre: 'Dance Pop', audioUrl: '/static/audio/jaaruko.mp3' },
      { id: 'sos4', name: 'Seethakaalam', duration: 309, genre: 'Romantic Melody', audioUrl: '/static/audio/seethakaalam.mp3' },
      { id: 'sos5', name: 'Super Machi', duration: 324, genre: 'Dance Pop', audioUrl: '/static/audio/super_machi.mp3' },
      { id: 'sos6', name: 'Vacchadu', duration: 201, genre: 'Dance Pop', audioUrl: '/static/audio/vacchadu.mp3' },
    ],
  },
  {
    id: 'mahanati',
    name: 'Mahanati',
    coverImage: '/static/images/mahanati.jpg',
    releaseYear: 2018,
    artist: 'Mickey J. Meyer',
    description: 'The spectacular award-winning biopic movie soundtrack composed by Mickey J. Meyer.',
    songs: [
      { id: 'mah1', name: 'Mahanati', duration: 296, genre: 'Romantic Melody', audioUrl: '/static/audio/mahanati.mp3' },
      { id: 'mah2', name: 'Mooga Manasulu', duration: 260, genre: 'Romantic Melody', audioUrl: '/static/audio/mooga_manasulu.mp3' },
      { id: 'mah3', name: 'Sada Nannu', duration: 211, genre: 'Classical Fusion', audioUrl: '/static/audio/sada_nannu.mp3' },
      { id: 'mah4', name: 'Aagipo Baalyama', duration: 261, genre: 'Romantic Melody', audioUrl: '/static/audio/aagipo_baalyama.mp3' },
      { id: 'mah5', name: 'Gelupuleni Samaram', duration: 197, genre: 'Romantic Melody', audioUrl: '/static/audio/gelupuleni_samaram.mp3' },
      { id: 'mah6', name: 'Chivaraku Migiledi', duration: 184, genre: 'Classical Fusion', audioUrl: '/static/audio/chivaraku_migiledi.mp3' },
    ],
  },
  {
    id: 'vunnadhi_okate_zindagi',
    name: 'Vunnadhi Okate Zindagi',
    coverImage: '/static/images/vunnadhi_okate_zindagi.jpg',
    releaseYear: 2017,
    artist: 'Devi Sri Prasad',
    description: 'A beautiful soundtrack centered around friendship and love, composed by Devi Sri Prasad.',
    songs: [
      { id: 'voz1', name: 'Vunnadhi Okate Zindagi Title Song', duration: 298, genre: 'Romantic Melody', audioUrl: '/static/audio/vunnadhi_okate_zindagi.mp3' },
      { id: 'voz2', name: 'Trend Maarina Friend Maaradu', duration: 251, genre: 'Dance Pop', audioUrl: '/static/audio/trend_marina_friend_maaradu.mp3' },
      { id: 'voz3', name: 'What Amma', duration: 303, genre: 'Dance Pop', audioUrl: '/static/audio/what_amma.mp3' },
      { id: 'voz4', name: 'Rayyi Rayyi Mantu', duration: 325, genre: 'Dance Pop', audioUrl: '/static/audio/rayyi_rayyi_mantu.mp3' },
      { id: 'voz5', name: 'Life Is A Rainbow', duration: 345, genre: 'Romantic Melody', audioUrl: '/static/audio/life_is_a_rainbow.mp3' }
    ],
  },
  {
    id: 'v',
    name: 'V',
    coverImage: '/static/images/v.jpg',
    releaseYear: 2020,
    artist: 'Amit Trivedi',
    description: 'A stylish and thrilling action thriller movie soundtrack composed by Amit Trivedi.',
    songs: [
      { id: 'v1', name: 'Manasu Maree', duration: 248, genre: 'Romantic Melody', audioUrl: '/static/audio/manasu_maree.mp3' },
      { id: 'v2', name: 'Vastunna Vachestunna', duration: 202, genre: 'Dance Pop', audioUrl: '/static/audio/vastunna_vachestunna.mp3' },
      { id: 'v3', name: 'Baby Touch Me Now', duration: 186, genre: 'Dance Pop', audioUrl: '/static/audio/baby_touch_me_now.mp3' },
      { id: 'v4', name: 'Ranga Rangeli', duration: 228, genre: 'Dance Pop', audioUrl: '/static/audio/ranga_rangeli.mp3' },
    ],
  },
  {
    id: 'darling',
    name: 'Darling',
    coverImage: '/static/images/darling.jpg',
    releaseYear: 2010,
    artist: 'G. V. Prakash Kumar',
    description: 'A brilliant and highly acclaimed romantic musical album composed by G. V. Prakash Kumar.',
    songs: [
      { id: 'dar1', name: 'Inka Edo', duration: 309, genre: 'Romantic Melody', audioUrl: '/static/audio/inka_edo.mp3' },
      { id: 'dar2', name: 'Neeve', duration: 280, genre: 'Romantic Melody', audioUrl: '/static/audio/neeve.mp3' },
      { id: 'dar3', name: 'Hosahore', duration: 226, genre: 'Dance Pop', audioUrl: '/static/audio/hosahore.mp3' },
      { id: 'dar4', name: 'Priyathama', duration: 260, genre: 'Romantic Melody', audioUrl: '/static/audio/priyathama.mp3' },
      { id: 'dar5', name: 'One Boy One Girl', duration: 244, genre: 'Dance Pop', audioUrl: '/static/audio/one_boy_one_girl.mp3' },
      { id: 'dar6', name: 'Bulle', duration: 267, genre: 'Dance Pop', audioUrl: '/static/audio/bulle.mp3' },
    ],
  },
  {
    id: 'majili',
    name: 'Majili',
    coverImage: '/static/images/majili.jpg',
    releaseYear: 2019,
    artist: 'Gopi Sundar',
    description: 'A beautiful emotional romantic drama movie soundtrack composed by Gopi Sundar.',
    songs: [
      { id: 'maj1', name: 'Priyathama Priyathama', duration: 243, genre: 'Romantic Melody', audioUrl: '/static/audio/priyathama_priyathama.mp3' },
      { id: 'maj2', name: 'Ye Manishike Majiliyo', duration: 260, genre: 'Romantic Melody', audioUrl: '/static/audio/ye_manishike_majiliyo.mp3' },
      { id: 'maj3', name: 'Yedetthu Mallele', duration: 200, genre: 'Romantic Melody', audioUrl: '/static/audio/yedetthu_mallele.mp3' },
      { id: 'maj4', name: 'Naa Gundello', duration: 287, genre: 'Romantic Melody', audioUrl: '/static/audio/naa_gundello.mp3' },
      { id: 'maj5', name: 'One & Two & Three', duration: 226, genre: 'Dance Pop', audioUrl: '/static/audio/one_two_three.mp3' },
      { id: 'maj6', name: 'Maayya Maayya', duration: 267, genre: 'Dance Pop', audioUrl: '/static/audio/maayya_maayya.mp3' },
    ],
  },
  {
    id: 'arjun',
    name: 'Arjun',
    coverImage: '/static/images/arjun.jpg',
    releaseYear: 2004,
    artist: 'Mani Sharma',
    description: 'The iconic blockbuster family-drama movie soundtrack composed by Mani Sharma.',
    songs: [
      { id: 'arj1', name: 'Madhura Madhure Meenakshi', duration: 320, genre: 'Romantic Melody', audioUrl: '/static/audio/madhura_madhuratara.mp3' },
      { id: 'arj2', name: 'Aey Pilla', duration: 250, genre: 'Romantic Melody', audioUrl: '/static/audio/aey_pilla.mp3' },
      { id: 'arj3', name: 'Dum Dumare', duration: 280, genre: 'Dance Pop', audioUrl: '/static/audio/dum_dumare.mp3' },
      { id: 'arj4', name: 'O Cheli Nee Oyyarale', duration: 300, genre: 'Romantic Melody', audioUrl: '/static/audio/o_cheli.mp3' },
      { id: 'arj5', name: 'Okka Maata', duration: 260, genre: 'Dance Pop', audioUrl: '/static/audio/okka_mata.mp3' },
      { id: 'arj6', name: 'Ra Ra Rajakumara', duration: 260, genre: 'Dance Pop', audioUrl: '/static/audio/raa_raa.mp3' },
    ],
  },
  {
    id: 'bahubali',
    name: 'Baahubali: The Beginning',
    coverImage: '/static/images/bahubali.jpg',
    releaseYear: 2015,
    artist: 'M. M. Keeravani',
    description: 'The monumental periodic epic movie soundtrack composed by M. M. Keeravani.',
    songs: [
      { id: 'bah1', name: 'Dhivara', duration: 343, genre: 'Romantic Melody', audioUrl: '/static/audio/dhivara.mp3' },
      { id: 'bah2', name: 'Mamatala Talli', duration: 204, genre: 'Classical Fusion', audioUrl: '/static/audio/mamathala_thalli.mp3' },
      { id: 'bah3', name: 'Manohari', duration: 232, genre: 'Dance Pop', audioUrl: '/static/audio/manohari.mp3' },
      { id: 'bah4', name: 'Sivuni Aana', duration: 325, genre: 'Classical Fusion', audioUrl: '/static/audio/sivuni_aana.mp3' },
      { id: 'bah5', name: 'Pacha Bottasi', duration: 273, genre: 'Romantic Melody', audioUrl: '/static/audio/pachha_bottasi.mp3' },
      { id: 'bah6', name: 'Jeeva Nadhi', duration: 112, genre: 'Classical Fusion', audioUrl: '/static/audio/jeeva_nadhi.mp3' },
      { id: 'bah7', name: 'Nippule Swasaga', duration: 203, genre: 'Classical Fusion', audioUrl: '/static/audio/nippule_swasaga.mp3' },
      { id: 'bah8', name: 'Dheevara (English Version)', duration: 206, genre: 'Romantic Melody', audioUrl: '/static/audio/dhivara_english.mp3' },
    ],
  },
  {
    id: 'peddi',
    name: 'Peddi',
    coverImage: '/static/images/peddi.jpg',
    releaseYear: 2026,
    artist: 'A. R. Rahman',
    description: 'The highly anticipated sports action movie soundtrack composed by Mozart of Madras A. R. Rahman.',
    songs: [
      { id: 'ped1', name: 'Chikiri Chikiri', duration: 248, genre: 'Classical Fusion', audioUrl: '/static/audio/chikiri_chikiri.mp3' },
      { id: 'ped2', name: 'Hellallallo', duration: 219, genre: 'Dance Pop', audioUrl: '/static/audio/hellallallo.mp3' },
      { id: 'ped3', name: 'Massa Massa', duration: 203, genre: 'Dance Pop', audioUrl: '/static/audio/massa_massa.mp3' },
      { id: 'ped4', name: 'Rai Rai Raa Raa', duration: 254, genre: 'Dance Pop', audioUrl: '/static/audio/rai_rai_raa_raa.mp3' },
    ],
  },
];
